Notes/urls.py
from django.urls import path
from . import views

app_name = 'Notes'
urlpatterns = [
   path('', views.IndexView.as_view(), name='index'),
   path('note/<str:pk>/', views.DetailView.as_view(), name='detail'),
   path('delete/<str:pk>/', views.DeleteNote.as_view(), name='delete'),
   path('update/<str:pk>/', views.UpdateNote.as_view(), name='update'),
   path('create', views.CreateNote, name='create'),
   path('newnote', views.NewNote.as_view(), name="newnote")
  
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('Notes.urls')),
]

Notes/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User

class NoteBook(models.Model):
   # user= models.ForeignKey(User,on_delete=models.CASCADE)  
    title = models.CharField(max_length=20, primary_key=True, blank=False)
    pub_date = models.DateTimeField('Date Created',auto_now_add=True)
    plain_note = models.TextField( max_length=1040, blank=False,)
    update_date = models.DateTimeField('Date Modified', auto_now=True)

    def was_created_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def was_updated_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.update_date <= now

    def get_absolute_url(self):
        return reverse('update', kwargs={'pk':self.pk})

    def __str__ (self):
        return "{}".format(self.title)
    
 

Notes/forms.py
from django.forms import ModelForm
from .models import NoteBook
from django import forms

class NotebookForm(forms.ModelForm):

    class Meta:
        model = NoteBook
        fields =['title','plain_note']

Notes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import NoteBook
from django.contrib import messages
from .forms import NotebookForm


# Create your views here.

class IndexView(generic.ListView):
    template_name = 'Notes/index.html'
    context_object_name = 'Notes_list'

    def get_queryset(self):
        #return NoteBook.objects.order_by('-pub_date')
        return NoteBook.objects.filter(pub_date__lte=timezone.now()).order_by('-update_date')


class DetailView(generic.DetailView):
    model = NoteBook
    template_name = 'Notes/detail.html'


class DeleteNote(generic.DeleteView):
    model = NoteBook
    success_url ="/"

class UpdateNote(generic.UpdateView):
    form_class = NotebookForm
    template_name = 'Notes/notebook_form_update.html'  
    update_date = timezone.now()
    success_url ="/note/{title}/"

    def get_object(self, queryset=None):
        title = self.kwargs.get('pk')
        return get_object_or_404(NoteBook, title=title)

    def form_valid(self, form):
        updated_title = form.cleaned_data['title']
        current_title = NoteBook.objects.get(pk=self.kwargs['pk'])
        if updated_title != current_title:
            self.get_object().delete()
        return super().form_valid(form)



""" class CreateNote(generic.CreateView):
    model = NoteBook
    template_name = 'Notes/notebook_form_add.html'    
    fields =['title','plain_note'] 
    success_url ="/" 
 """
class NewNote(generic.TemplateView):
    template_name = 'Notes/add.html' 

def CreateNote(request):
    title=request.POST["title"]
    plain_note = request.POST["plain_note"]

    if title=="" or  plain_note=="":
        messages.warning(request, "please provide a title and content for your note")
        return HttpResponseRedirect(reverse('Notes:index'))

    if NoteBook.objects.filter(pk=title).exists() !=True:
        notekeeper = NoteBook(title,timezone.now(),plain_note,timezone.now())
        notekeeper.save()
        messages.success(request, "New note has been created")
        return HttpResponseRedirect(reverse('Notes:index'))
    messages.warning(request, "Title is in use, Try using another name!")
    return HttpResponseRedirect(reverse('Notes:index'))


""" class NoteUpdate(generic.TemplateView):
   template_name = 'Notes/notebook_form_update.html'  
def UpdateNote(request):
    title=request.POST["title"]
    plain_note = request.POST["plain_note"]
    object,filter
    notekeeper = NoteBook(title,timezone.now(),plain_note,timezone.now())
    notekeeper.save()
    return HttpResponseRedirect(reverse('Notes:index')) """

Notes/templates/Notes/add.html
{% extends "Notes/page_structure.html" %}

{% block heading %} 
<a href={% url 'Notes:index' %} class="go-back">&#60 Cancel</a>Creating New Note
{% endblock %}

{% block date %} 
    {% now " F jS, Y " %}   
{% endblock %}  

{% block mynotes %}
<form method="POST" action="{% url 'Notes:create' %}" class="add">
    {% csrf_token %}
 
    <input type="text" id="title" name="title" required="required" placeholder="What is the TITLE of your note" class="title"> </br>

 
    <textarea type="text" id="plain_note" name="plain_note" required="required" placeholder="You can type the content of your note here. And when you are done please click on the Add button bellow"></textarea></br>
    <button type="submit" value="">Add Note</button>
</form>

{% endblock mynotes %}



  <!--  <form method="POST" action="{% url 'Notes:create' %}" class="add">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Add Note">
    </form> -->

Notes/templates/Notes/detail.html
{% extends "Notes/page_structure.html" %}



{% block heading %} 
	
	<a href={% url 'Notes:index' %} class="go-back">&#60 back</a> {{ notebook.title }} 

	
{% endblock %}

{% block date %} 
	{{ notebook.pub_date |date:"M d, Y H:i"}}
{% endblock %}  

{% block mynotes %}
{% load static %} 
	{% if notebook %}
	<div class="icons-update-delete">
	<a class="delete-update-btn" href="{% url 'Notes:update' notebook.title %}"><img class="icon-images" src="{% static 'Notes/images/edit.svg' %}"> Edit</a>
	<a class="delete-update-btn" href="{% url 'Notes:delete' notebook.title %}"><img class="icon-images" src="{% static 'Notes/images/delete.svg' %}"> Delete</a> 
	</div>
		<p class="updated-on">last updated on {{notebook.update_date}} </p>
		<p class="notes plain-notes">{{ notebook.plain_note}}</p>
        {% else %}
		<p class="emptyContent">The note is currently empty, would you like to add conttent</p>
		
		{% endif %} 
		
{% endblock mynotes %}	

Notes/templates/Notes/index.html
{% extends "Notes/page_structure.html" %}

{% block heading %} 
	My Notes  <a href="{% url 'Notes:newnote'  %}">&plus; add</a> 
	<!-- <span style="color: black; font-size: 14px;">&#60; Previous</span>
	<span style="color: black; font-size: 14px;">&plus;</span> -->
{% endblock %}

{% block date %} 
	{% now " F jS, Y " %}
{% endblock %}  

{% block mynotes %}
		 {% if Notes_list %}
		 <ol>
			{% for note in Notes_list %}
				<li class="notes-list"><a href="{% url 'Notes:detail' note.title %}">{{ note.title }}  </a></li> 
		
		    {% endfor %}
		</ol>
		
        {% else %}
		    <p class="emptyContent">Your NoteBook is currently empty. To create new notes, click add </p>
			{% endif %} 
{% endblock mynotes %}	

Notes/templates/Notes/notebook_confirm_delete.html
{% extends "Notes/page_structure.html" %}

{% block heading %} 
<a href={% url 'Notes:index' %} class="go-back">&#60 Cancel</a>Delete Confirmation!
{% endblock %}

{% block date %} 
    {% now "M H, Y" %}
{% endblock %}  

{% block mynotes %}
    <form method="POST">
        {% csrf_token %}
        <p class="delete-confirmation">Are you sure you want to delete </br><strong> "{{ object }}"</strong>?</p>
        <button type="submit" class="confirm">Yes, Delete</button>
    </form>

{% endblock mynotes %}

Notes/templates/Notes/notebook_form_update.html
{% extends "Notes/page_structure.html" %}

{% block heading %} 
<a href={% url 'Notes:index' %} class="go-back">&#60 Cancel</a> Updating: {{notebook.title}}
{% endblock %}

{% block date %} 
    {% now " F jS, Y " %}
{% endblock %}  

{% block mynotes %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">update and continue</button>
    </form>

{% endblock mynotes %}

Notes/templates/Notes/page_structure.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'Notes/page_style.css' %}">
    <link rel="icon" href="{% static 'Notes/images/favicon.svg' %}" type="image/x-icon"/>
    <title>My Notes</title>
</head>
<body>
    <div class="paper">
        <div class="lines">
          <div class="text">
            <p class="datee">{% block date %} date{% endblock  %}</p>
            <h1>{% block heading %} heading {% endblock %} </h1>
            {% block mynotes %}
            content
            {% endblock mynotes %}

            {% for message in messages %}
            <div role="alert" class="msg">
             <p>{{ message }}</p> 
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="holes hole-top"></div>
        <div class="holes hole-middle"></div>
        <div class="holes hole-bottom"></div>

        

       
        <footer>Created by dankazim | March 19, 2021</footer>
       
    </div>
   
</body>
</html>

<!-- <script>
        window.ub.form.validationMessages.title = 'Please write the title of your note';
        window.ub.form.validationMessages.plain_note = 'Please write content for your note';
</script> -->